[package]
name = "resourcepacker"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
png = "0.16"
zip = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"